security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateurs: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_missions_index
                always_use_default_target_path: true
                username_parameter: _username
                password_parameter: _password
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
