# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# config/routes.yaml

# Routes principales
app_home:
    path: /
    controller: App\Controller\MissionController::index
    methods: GET

app_mission_index:
    path: /missions
    controller: App\Controller\MissionController::index
    methods: GET

app_mission_show:
    path: /mission/{id}
    controller: App\Controller\MissionController::show
    requirements:
        id: '\d+'
    methods: GET

app_missions_filter:
    path: /missions/filter
    controller: App\Controller\MissionController::filter
    methods: GET

# Routes d'authentification (de votre LoginController)
app_login:
    path: /connexion
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_logout:
    path: /deconnexion
    controller: App\Controller\LoginController::logout
    methods: GET

app_register:
    path: /inscription
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /

app_mission_creer:
    path: /mission/creer
    controller: App\Controller\MissionController::creerMission
    methods: [GET, POST]

app_mission_edit:
    path: /mission/{id}/edit
    controller: App\Controller\MissionController::editMission
    requirements:
        id: '\d+'
    methods: [GET, POST]

app_mission_delete:
    path: /mission/{id}/delete
    controller: App\Controller\MissionController::deleteMission
    methods: POST