# config/routes.yaml
app_mission_index:
    path: /missions
    controller: App\Controller\MissionController::index
    methods: GET

app_mission_show:
    path: /mission/{id}
    controller: App\Controller\MissionController::show
    requirements:
        id: '\d+'
    methods: GET

app_missions_filter:
    path: /missions/filter
    controller: App\Controller\MissionController::filter
    methods: GET

app_mission_creer:
    path: /mission/creer
    controller: App\Controller\MissionController::creerMission
    methods: [GET, POST]

app_mission_edit:
    path: /mission/{id}/edit
    controller: App\Controller\MissionController::editMission
    requirements:
        id: '\d+'
    methods: [GET, POST]

app_mission_delete:
    path: /mission/{id}/delete
    controller: App\Controller\MissionController::deleteMission
    methods: POST

# Routes d'authentification
app_login:
    path: /connexion
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_logout:
    path: /deconnexion
    controller: App\Controller\LoginController::logout
    methods: GET

app_register:
    path: /inscription
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

# Import automatique des autres routes avec attributs
controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /
